merge ipa-6.1.1.rc to main (#100)
* [DOP-1500] 6.1.0.rc (#85)

* [DOP-1500] Include Variable to optionally allow access to indico-locust-benchmark-test-results s3 bucket. this is disabled by default.

* [DOP-1500] Fix parenthesis location.

* Update ipa.tf

* Updating blob to be private

* Update ipa.tf

* Workload Identity Patch [DOP-1535] (#90)

* Remove workload identity from aws

* Add workload identity to azure

* Update ipa.tf

* Storage requirement

https://app.terraform.io/app/indico/workspaces/indico-dev-azure-eastus-tulip/runs/run-tAucN64D5nRk2PCo

Error: current client lacks permissions to read Key Rotation Policy for Key "tulip-key" ("Vault: (Name \"kv-eastus-tulip\" / Resource Group \"tulip-eastus\")", Vault url: "https://kv-eastus-tulip.vault.azure.net/"), please update this as described here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_key#example-usage : keyvault.BaseClient#GetKeyRotationPolicy: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=52707cf2-4e6f-4520-8aa5-a8c91d2a9a78;oid=0d31e023-f762-4f83-ae97-243fd8db7f94;numgroups=1;iss=https://sts.windows.net/fa172214-f33c-406c-8078-95266bd1470b/' does not have keys getrotationpolicy permission on key vault 'kv-eastus-tulip;location=eastus'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287" InnerError={"code":"ForbiddenByPolicy"}

* Added space to retrigger tulip plan

* Refactor openshift (#96)

* Fix NFD kind/version

* Fix dependency

* Fix dependency

* Fix dependency

* Fix dependency

* Fix dependency

* Wait till available

* Wait till available

* Add clusterpolicy for nvidia

* Fixed cp def

* Fixed cp def

* Finish out spec for CP

* Changed SKU for GPU

* Changed SKU for GPU

* Put GPUs into no-zone(0)

* Install the postgres database into the crunchy namespace

* Use no-zone for GPU

* Fixed dependency for crds

* Fixed dependency for crds

* Update defaults for crunchy installation to make similar to aws install.

* Use an azure published profile

* Fixed spelling of strimzi

* Fixed initial dependencies

* Fixed initial dependencies

* Fixed initial dependencies

* Fixed initial dependencies

* Switched to kubectl_manifest becuase kubernetes_manifest requires the objects to exist at plan time

* Switched to kubectl_manifest becuase kubernetes_manifest requires the objects to exist at plan time

* Switched to kubectl_manifest becuase kubernetes_manifest requires the objects to exist at plan time

* Switched to kubectl_manifest becuase kubernetes_manifest requires the objects to exist at plan time

* Unset default storage class

* Fixed dependency for unsetting default sc

* Wait for ready on subscriptions

* Fixed RG name

* Fixed RG name

* Fixed wait script

* Fixed gpu operator

* Fixed gpu operator

* Fixed dependencies

* Fixed dependencies

* Fixed dependencies

* Use random string for auth

* Cleanup files

* Cleanup files

* Generate random prefix

* Cleanup random files

* Wait for cluster

* Wait for cluster

* Fixed auth prefix

* Fixed servicemonitor

* Enable openshift for reloader

* Update CRDs to support openshift reloader

* Wait for namespace as well

* Wait for all previous operators

* Wait for ready on NFD

* Show progression status

* Show progressions

* Re-enable monitoring

* Disable postgres-exporter for monitoring on openshift

* Disable kube-prometheus-stack on openshift

* Qualify ready for NFD

* Debug ready

* Enable rabbit servicemonitor

* Enable metrics

* Enable ServiceMonitor under rabbit metrics

* Nest rabbit config under rabbit

* Enable ServiceMonitors for KEDA

* Create prometheu service for keda

* Create prometheu service for keda

* Create prometheu service for keda

* UPdate address

* Dont install Keda on openshift, use the redhat operator instead

* Added openshift keda subscription

* Added redhat keda

* Fixed YAML inline

* Use thanos querier for Keda on openshift

* Deploy our own keda

* Use Openshift Keda and configure Keda Controller

* Create Querier SA for Thanos

* Add CRB to querier

* Create reflected secret for querying Thanos

* Create openshift keda namespace

* Create openshift keda namespace

* Create openshift keda namespace

* Wait additional 30 seconds

* Move all to openshift-monitoring

* Create querier in the default namespace

* Remove autoscaler

* Install custom metrics autoscaler

* Create TriggerAuth

* Create TriggerAuth

* Enable auth for ScaledObjects

* Fix dependency ref to secret

* Enable secure http for thanos

* Enable CRB for querier sa

* Move SA to openshift-keda

* Switch to CA

* Switch to 9091

* Change default vm for openshift worker nodes

* Wait for controller

* Install OperatorGroup

* Use newer node-feature-discovery image

* Pass in Prometheus URL to smoketest

* Testing destroy

* Testing destroy

* Delete the cluster on a destroy

* Remove finalizer on destroy

* Remove finalizer on destroy

* Remove finalizer on destroy

* Login first before destroy

* Login first before destroy

* Link to auth.sh

* Always return true

* Dont escape command

* Always return true

* Remove blank line

* Patch namespace on destroy

* Auth before patching

* Auth before patching

* Auth path on destroy

* Use null resource to remove nfd finalizer

* Use null resource to remove nfd finalizer

* Added unlink script

* Pass in openshift pull secret

* Added vault provider

* Added vault provider

* Igmnore .env files

* Make snapshots enableable

* Pass in vault mount

* Reuse mount path

* hide login output

* Fixed data mount path for secret

* Update variables.tf

* Disable cluster-manager, module is broken

* Reenable the cluster-manager

* Quote variables for comparisons

* Fixed dependencies

* Fixed dependencies

* Fixed dependencies

* Fixed wait

* Use login then patch

* Renamed script

* Fixed resource group name

* Move where we create the default sc

* Add dependency on monitoring

* Fixed dependencies

* Use terraform repo for secrets for zerossl

* Refactor to new openshift

* More updates

* Updates

* Added new files

* Completed create and infrastructure

* Added datasources for infra

* Moved datasources into seperate file

* Reducing variables

* Remove unused vars

* Added new locals

* Remove unused vars

* Move creation of GPU machinesets to infrastructure

* Create default sc as part of infra

* Added missing file

* Use get_token for auth

* Added missing file

* Fixed auth links

* Added Rotation Policies

* Replace prom crds

* Fixed rg name ref

* Fixed spelling

* Fixed RG name

* Fixed path to replace crds

* Fixed CRD to remove nginx

* Always replace CRDs

* Scale down operator before replacing CRDs and installing the kube prometheus stack

* Scale down prom operators first

* Scale down/up cluster version operator to replace crds and install kube-prometheus-stack

* Use correct version for IPA crds

* Use the correct version for openshift-crds

* Update scc policy

* Use OC for adm

* use monitoring namespace for keda

* Disable postgres export3er

* Added in all of the infra files

* Added in all of the infra files

* Added monitoring namespace variable

* Pre-reqs as part of infrastructure

* Switched default namespace to indico for openshift

* Resolved external dns for openshift

* Create the indico namespace

* Turn off external dns

* Allow other namespaces

* Move CRDS back to default

* Put secret into default for CRDs

* Put PS in ipa crds namespace

* Install crunchy into its own namespace

* Allow any container

* Namespace the storage key

* Temp disable argo

* Set the secret namespace

* Fixed storage account name

* Parameterized test namespace

* Fixed login script to use sa name

* Fixed parameterizing terraform-sa

* Enable openshift

* Move to IPA

* MOve CRDs to indico

* MOve CRDs to indico

* Disable node exporter

* Fixed thypo

* Enable rabbit monitoring

* Re-run kube-prom stack

* Rabbit is already enabled

* Try to get prom again

* Trigger a re-deploy

* Testing fake entry

* Replace the CRDs only 1 time

* Remove fake entries

* Disable un-used triggers

* Include the Indico admission controller

* Modularized the openshift specific infrastructure

* Fixed admission controller dependency

* Switched order for adm controller dependencis

* Updated chart version

* Install IPA

* Enable IPA with namespace

* Enable IPA with namespace

* Fixed dependency

* Pre-install the self-signed issuer

* Enable argo and IPA

* Enable metrics server

* Disable metrics server

* Enable metrics server on openshift

* Enable prometheus monitor for rabbit and runtime scanner

* Dont install Rabbitmq service monitor since it is already scraped by the prometheus labels

* Enable smoketest

* Deploy the smoketests

* Dont enable apiservice

* Update smoketest version

* Fixed smoketest namespace

* Load the workload identity secret

* Add env. vars for auth for Azure based on env. vars

* Modify the kafka postgres service path

* Remove whitespace

* Cleanup kafka

* Include azure storage key secret

---------

Co-authored-by: NathanOkolita <nathan.okolita@gmail.com>
Co-authored-by: Andrey Chmykh <andrey.chmykh@indico.io>

* Removed alpha openshift version

* Allow for customized storage account names (#97)

---------

Co-authored-by: Nathan Okolita <Nathan.Okolita@gmail.com>
Co-authored-by: Andrey Chmykh <andrey.chmykh@indico.io>
Co-authored-by: Liz Lemon <liz.lemon@indicodata.ai>